# Cloudflare Pages Build Configuration

# Build command
[build]
command = "pip install -r requirements.txt && mkdocs build"
publish = "site"

# Environment variables
[build.environment]
PYTHON_VERSION = "3.11"

# Build settings
[build.processing]
minify = true

[build.processing.css]
minify = true

[build.processing.js]
minify = true

[build.processing.html]
minify = true

# Headers for security and performance
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# Redirects
[[redirects]]
from = "/tools/*"
to = "/tools/:splat"
status = 200

# Custom 404 page
[[redirects]]
from = "/*"
to = "/404.html"
status = 404